name: rt-n56u-auto-sync

on:
  push:
    branches:
      -master
  workflow_dispatch:
  #schedule:
   # - cron: 0/1 * * * *   # 每隔12小时
  watch:                                                        # 监视操作
    types: [started]                                            # 点击 Star 之后
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: hanwckf/rt-n56u  # 上游仓库
          target_repository: dylan8888/rt-n56u  # 你要推送的仓库
          upstream_branch: master  # 默认是拉取上游仓库的master分支
          target_branch: master  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags
